name: CI

on:
  push:
    branches:
      - main
      - next
  pull_request:
    branches:
      - main

jobs:
  publish:
    name: "Publish"
    needs: test-adapters
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: "12"
      - uses: bahmutov/npm-install@v1
      - name: Test (changed packages)
        run: lerna run test --since HEAD~
      - name: Build (changed packages)
        run: lerna run build --since HEAD~
      - name: Authenticate with NPM
        run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
      - name: Configure CI Git User
        run: |
          git config --global user.email nextauth@gmail.com
          git config --global user.name "NextAuth.js"
          git config remote.origin.url https://x-access-token:$GH_PAT@github.com/$GITHUB_REPOSITORY
      - name: Publish to @next
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/next' }}
        run: |
          lerna publish --canary --preid next \
          --dist-tag next --conventional-prerelease \
          --create-release github --yes
      - name: Publish to @experimental
        if: ${{ github.base_ref == 'main' }}
        run: |
          git checkout ${{ github.head_ref }}
          lerna publish \
          --preid pr.${{ github.event.number }}-${GITHUB_SHA::8} \
          --canary --dist-tag experimental --yes
      - name: Publish to @latest
        if: ${{github.event_name == 'push' && github.ref == 'refs/heads/main'}}
        run: lerna publish --create-release github --yes
